[package]
name = "forest"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.7.0"
minibytes = { path = "third-party/minibytes", default_features = false, features = ["frommmap"] }
smallvec = "1.13.2"

[dev-dependencies]
rand = "0.8.5"
